---
title: "Code_Book"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
***
### Overview

This code book is to explain the "Human Activity Recognition Using Smartphones Dataset" that is used in the project. It first explains the experiment that was used to collect the data, then explains the sub-datasets, and finally explains the variables.

***
### Experiment

Human Activity Recognition Using Smartphones Dataset  
    Version 1.0  
    Jorge L. Reyes-Ortiz, Davide Anguita, Alessandro Ghio, Luca Oneto.  
    Smartlab - Non Linear Complex Systems Laboratory  
    DITEN - Università degli Studi di Genova.  
    Via Opera Pia 11A, I-16145, Genoa, Italy.  
    activityrecognition@smartlab.ws  
    www.smartlab.ws  

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain. See 'features_info.txt' for more details.

***
### Sub-datasets

* 'features_info.txt': Shows information about the variables used on the feature vector.

* 'features.txt': List of all features.

* 'activity_labels.txt': Links the class labels with their activity name.

* 'train/X_train.txt': Training set.

* 'train/y_train.txt': Training labels.

* 'test/X_test.txt': Test set.

* 'test/y_test.txt': Test labels.

* 'train/subject_train.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30. 

* 'train/Inertial Signals/total_acc_x_train.txt': The acceleration signal from the smartphone accelerometer X axis in standard gravity units 'g'. Every row shows a 128 element vector. The same description applies for the 'total_acc_x_train.txt' and 'total_acc_z_train.txt' files for the Y and Z axis. 

* 'train/Inertial Signals/body_acc_x_train.txt': The body acceleration signal obtained by subtracting the gravity from the total acceleration. 

* 'train/Inertial Signals/body_gyro_x_train.txt': The angular velocity vector measured by the gyroscope for each window sample. The units are radians/second. 

***
### Variables


#### Original Dataset


##### Features
A total of 561 "feature" variables are included in the data. They represent different **Signals** and **Measurements**.

* Signals 
    + tBodyAcc-XYZ
    + tGravityAcc-XYZ
    + tBodyAccJerk-XYZ
    + tBodyGyro-XYZ
    + tBodyGyroJerk-XYZ
    + tBodyAccMag
    + tGravityAccMag
    + tBodyAccJerkMag
    + tBodyGyroMag
    + tBodyGyroJerkMag
    + fBodyAcc-XYZ
    + fBodyAccJerk-XYZ
    + fBodyGyro-XYZ
    + fBodyAccMag
    + fBodyAccJerkMag
    + fBodyGyroMag
    + fBodyGyroJerkMag  
  
* Additonal Signals on used on the angle() variable:
    + gravityMean
    + tBodyAccMean
    + tBodyAccJerkMean
    + tBodyGyroMean
    + tBodyGyroJerkMean

* Variables to measure the signals:
    + mean(): Mean value
    + std(): Standard deviation
    + mad(): Median absolute deviation 
    + max(): Largest value in array
    + min(): Smallest value in array
    + sma(): Signal magnitude area
    + energy(): Energy measure. Sum of the squares divided by the number of values. 
    + iqr(): Interquartile range 
    + entropy(): Signal entropy
    + arCoeff(): Autorregresion coefficients with Burg order equal to 4
    + correlation(): correlation coefficient between two signals
    + maxInds(): index of the frequency component with largest magnitude
    + meanFreq(): Weighted average of the frequency components to obtain a mean frequency
    + skewness(): skewness of the frequency domain signal 
    + kurtosis(): kurtosis of the frequency domain signal 
    + bandsEnergy(): Energy of a frequency interval within the 64 bins of the FFT of each window.
    + angle(): Angle between to vectors.


##### Activities

* Six types of activities are included:
    + 1: WALKING
    + 2: WALKING_UPSTAIRS
    + 3: WALKING_DOWNSTAIRS
    + 4: SITTING
    + 5: STANDING
    + 6: LAYING


#### Tidy Dataset "average_data.txt"

The dataset has 100 observations of 180 variables.

* "subject": 1-30, including 20 from the train set and 10 from the test set  
* "activity": 6 types of activities, named with the descriptive name of each activity  
* the other variables shows the measurements of the features
